### ISSUE TITLE
SSJS has a non-efficient setup

### ISSUE THREAD

**Issue by jpaynesalesforce** [email360/ssjs-lib#12]
Long story, but more or less, using a text field of length 4000, as part of a Primary Key, violates PK maximum lengths allowed. There are more issues as well, which I can explain if you wish to discuss it further (but should not be done in a public forum). Reach out to me: jpayne@salesforce.com

More or less this automatic declaration of the long text field as part of a PK is causing issues and so going forward anyone using this cannot have those fields as part of PK. For cleanup, I need to now go through and drop the PKs on all the Data Extensions created from this script and then rebuild them, so they do not include "message".

See this [code](https://github.com/email360/ssjs-lib/blob/master/setup/setup.ssjs), and if line 256 could be changed to be this:
` { "Name": "message", "FieldType": "Text", "MaxLength": 4000, "IsRequired": true },`
That would fix the issue for anyone using the code going forward.

Thank you. Reach out to discuss please.

**Comment by shdinx** [comment]
merged
