### ISSUE TITLE
Object expected error

### ISSUE THREAD

**Issue by arthurnoort** [email360/ssjs-lib#4]
Hi, 

First of all thank you for this great library. I have just started using it but I am running into an issue when using any DE function, e.g. copyDataExtension. It gives me the error below. I tried several different DEs, sendable non-sendable, etc. Any idea what causes this and how I can fix it?

{{"message":"Object expected: copyDataExtension","jintException":"Jint.Native.JsException: Exception of type 'Jint.Native.JsException' was thrown.\r\n at Jint.ExecutionVisitor.Visit(MethodCall methodCall)\r\n at Jint.Expressions.MethodCall.Accept(IJintVisitor visitor)\r\n at Jint.ExecutionVisitor.Visit(MemberExpression expression)\r\n at Jint.Expressions.MemberExpression.Accept(IJintVisitor visitor)\r\n at Jint.ExecutionVisitor.Visit(ExpressionStatement statement)\r\n at Jint.Expressions.ExpressionStatement.Accept(IJintVisitor visitor)\r\n at Jint.ExecutionVisitor.Visit(BlockStatement statement)\r\n at Jint.Expressions.BlockStatement.Accept(IJintVisitor visitor)\r\n at Jint.ExecutionVisitor.Visit(TryStatement statement)","description":"Jint.Native.JsException: Object expected: copyDataExtension\r\nException of type 'Jint.Native.JsException' was thrown. - from Jint\r\n\r\n"}} asdasdas

**Comment by shdinx** [comment]
Hi @arthurnoort 

copyDataExtension is part of [wsproxy](https://github.com/email360/ssjs-lib/blob/049534dd44feba90e641bf767828cd221a5e2235/core/lib_wsproxy.ssjs).
You need to create a new instance of wsproxy first such as this:

`var prox = new wsproxy();
  var resp = prox.copyDataExtension("Staging_Trigger_billing_onboarding", "test", true, 311269);`

I will add more sample code to the doc but also will cover those on the youtube channel.

Hope this helps

**Comment by arthurnoort** [comment]
Ah now I see the structure. Thanks this works really nicely.
